### ISSUE TITLE
Add installation guideline to readme

### ISSUE THREAD

**Issue by sipka** [tue-mdse/genderComputer#7]
Hello - perhaps I am being daft (sorry!) but I am struggling to install or use this package.
Would it be possible to add a few lines in the readme on best practices for installing? 
I have attempted with pip and with cloning locally but I must be doing something wrong and a few line guide would be of great help to future struggling noobs. :)
Thanks a lot

**Comment by aserebrenik** [comment]
@bvasiles can you please help?

**Comment by bvasiles** [comment]
Hi @sipka,

Would be great to package this so it's available through pip! 

Until then, download the code into the same folder as the script you're calling it from.
